### ISSUE TITLE
ground_speed ≠ to u_speed + v_speed

### ISSUE THREAD

**Issue by peterdesmet** [enram/case-study#22]
The hackathon participants discovered that `ground_speed` is not always equal to the root of `u_speed`<sup>2</sup> + `v_speed`<sup>2</sup>. These differences appear in the decimals.

Maybe we should recalculate the values using CartoDB?

**Comment by jshamoun** [comment]
It could be that different programs have different rounding issues, perhaps should be recalculated. Most important is do document which program was used to calculate the ground speed used in a given visualization.

**Comment by peterdesmet** [comment]
@hvangasteren, can you explain differences? Any idea where these are coming from?
