### ISSUE TITLE
Get forward trajectory data

### ISSUE THREAD

**Issue by peterdesmet** [enram/case-study#23]
## Datasets

* [x] From night of 6-7 april 2013
* [x] From night of 7-8 april 2013

## Scope

* [x] From WIER radar: 100 birds spawning for 4 half hours
* [x] From GLONS radar: 100 birds spawning for 4 half hours
* [x] From particles over NW Europe: 2000 particles spawning for 1 half hour
* [x] From sunset to sunrise (17h - 6h: 13hours)
* [x] Time interval: every 5 minutes

## Fields

* [ ] track_id: won't be used by Torque, but could be useful for other visualizations
* [x] date_time: `YYYY-MM-DD HH:MM:00Z`
* [x] latitude
* [x] longitude
* [x] start_time_id: a number, to group particles spawned at the same time
* [x] radar_id: could be text

**Comment by peterdesmet** [comment]
@hvangasteren, the requirements for the data are above. We'll see if it's feasible, because it might be to much.

**Comment by peterdesmet** [comment]
Updated requirements: if possible, two datasets might be the most convenient: one for each night.

**Comment by hvangasteren** [comment]
Done! Two files with the fields described at FIELDS.

Note that 
radar_id = 1 (Wier radar in N-Netherlands)
radar_id = 2 (Glons radar in SE Belgium)
radar_id = 3 Wind data

**Comment by peterdesmet** [comment]
I noticed that airspeed = 0 for wind. Would probably be better if set to `null`?

In the first dataset (6-7) there seem to be two issues: the start_time buckets are not synchronized and the dataset does not contain airspeed.

**Comment by hvangasteren** [comment]
airspeed for wind needs to be 0. Movement by wind of particles (airspeed=0) is then completely wind driven.
Start_time buckets need indeed be loaded agains, with start_time as sunset -10 minutes. Furthermore airspeed in this dataset needs to be added too.
