### ISSUE TITLE
Describe forward trajectory data in README

### ISSUE THREAD

**Issue by peterdesmet** [enram/case-study#24]
* [x] Upload data
* [x] Title
* [x] Introduction
* [x] Description
* [x] Data link
* [x] License
* [x] Contact

**Comment by peterdesmet** [comment]
@hvangasteren, can you review the text at https://github.com/enram/case-study/blob/master/data/forward-trajectory/README.md?

Notes:

* [ ] Is the methodology OK (adapted from blog post)
* [ ] Is the license (CC0) OK?
* [ ] Can you give me the coordinates of the two radars?

**Comment by hvangasteren** [comment]
The radar locations can't be shared, but the names in the descriptions should be precise enough.

**Comment by peterdesmet** [comment]
No problem. Is the rest of the text OK?

**Comment by hvangasteren** [comment]
Jazeker

 

Van: Peter Desmet [mailto:notifications@github.com] 
Verzonden: dinsdag 23 juni 2015 20:40
Aan: enram/case-study
CC: Hans van Gasteren
Onderwerp: Re: [case-study] Describe forward trajectory data in README (#24)

 

No problem. Is the rest of the text OK?
